"""update payback

Revision ID: 10561ecdd37d
Revises: c52600e16dba
Create Date: 2022-04-05 16:50:36.873855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10561ecdd37d'
down_revision = 'c52600e16dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdppayback',
    sa.Column('STT', sa.Integer(), nullable=False),
    sa.Column('depositor', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('STT')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cdppayback')
    # ### end Alembic commands ###
