"""update cdp

Revision ID: c52600e16dba
Revises: 561f149c1864
Create Date: 2022-04-05 01:18:42.707242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52600e16dba'
down_revision = '561f149c1864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdp', sa.Column('margin', sa.FLOAT(precision=10), nullable=False))
    op.add_column('cdp', sa.Column('code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdp', 'code')
    op.drop_column('cdp', 'margin')
    # ### end Alembic commands ###
